# Generated by Django 4.1.5 on 2023-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_address', models.CharField(max_length=100)),
                ('Customer_phone', models.IntegerField()),
            ],
        ),
    ]
