# Generated by Django 4.1.5 on 2023-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_name', models.CharField(max_length=100)),
                ('Phone_color', models.CharField(max_length=100)),
                ('Phone_price', models.IntegerField()),
            ],
        ),
    ]
